### PR TITLE
fix(dialogflow): remove the cmd options

### LINKED ISSUE #1302: dialogflow: samples have incorrect imports
For example, dialogflow/detect_intent/detect_intent.go has `"flag"` in the import block, but it isn't used in any of the samples.

We should either delete the command line interfaces or move each sample into its own file so the imports will always be correct. I'd prefer separate files. https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md#one-file-per-sample

Also, the sample functions should not be exported (https://github.com/GoogleCloudPlatform/golang-samples/blob/master/CONTRIBUTING.md#dont-export-sample-functions). For example, `DetectIntentStream`.

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #1302

### CODE REVIEW

File: dialogflow/intent_management/intent_management.go [hunk 1]
```diff
@@ -12,114 +12,20 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-package main
+package intent_mgmt
```
Comment (tbpg) [inline dialogflow/intent_management/intent_management.go:15]: `intent` or `intentmanagement` or `intentmgmt` (no underscore).

https://golang.org/doc/effective_go.html#package-names

File: dialogflow/intent_management/intent_management_test.go [hunk 2]
```diff
@@ -12,14 +12,13 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
-package main
+package intent_mgmt
```
Comment (tbpg) [inline dialogflow/intent_management/intent_management_test.go:15]: Update to match.

**Review by tbpg — CHANGES_REQUESTED** [review]
Thank you! One small package name comment.

**Review by tbpg — APPROVED** [review]
Thanks!
