### PR TITLE
test(all): remove all references to CleanBucket

### LINKED ISSUE #3565: storage/objects: TestObjects failed
Note: #2885 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: f2e5277497d1dd2c6f4d435fadbf486382680bae
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/ca622c8d-d7fa-49a8-a574-7d5b43509481), [Sponge](http://sponge2/ca622c8d-d7fa-49a8-a574-7d5b43509481)
status: failed

### PR DESCRIPTION
**Pull request by BrennaEpp**
## Description

Fixes #3565

Bumps the version of golang-samples to pick up changes to testutil. Replaces references to `CleanBucket` with methods that include bucket cleanup and error checking.

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

File: internal/testutil/storage_cleaner.go [hunk 1]
```diff
@@ -165,20 +120,8 @@ func DeleteBucketIfExists(ctx context.Context, client *storage.Client, bucket st
...
-			// Bucket does not exist
-			r.Errorf("Bucket was not created")
-			return
-		}
-	})
-}
-
-// UniqueBucketName returns a unique name with the test prefix.
+// UniqueBucketName returns a unique name with the test prefix
+// Any bucket created with this prefix may be deleted by DeleteExpiredBuckets.
```
Comment (tritone) [inline internal/testutil/storage_cleaner.go:124]: Is this actually true?

If so we should be sure to leave bucket prefixes alone for existing tests so we don't accidentally try to delete any buckets that people want to save.

**Review by tritone — COMMENTED** [review]
One comment regarding prefixes; otherwise seems good.

File: internal/testutil/storage_cleaner.go (hunk 1 above)
Comment (BrennaEpp) [reply internal/testutil/storage_cleaner.go:124]: Hmm, so it's true in that it "may" be lol. That is, if you call `DeleteExpiredBuckets` with the same prefix, which we do in storage tests I believe, those buckets will be deleted. But it's confusing, so I'll delete this comment. We definitely aren't storing prefixes and then deleting buckets based on that.

Comment (tritone) [reply internal/testutil/storage_cleaner.go]: Could you double check that you haven't changed prefixes for anything that does use DeleteExpiredBuckets? Otherwise we are good I'd say.

**Review by tritone — APPROVED** [review]

File: internal/testutil/storage_cleaner.go (hunk 1 above)
Comment (BrennaEpp) [reply internal/testutil/storage_cleaner.go]: Check done - nothing to note.
