### PR TITLE
spanner: add a sleep time to fix the flaky test.

### LINKED ISSUE #1146: spanner/spanner_snippets: TestSample failed
spanner/spanner_snippets: TestSample failed
buildID: IGNORE
buildURL: http://example.com
status: failed

### PR DESCRIPTION
**Pull request by hengfengli**
Fixes #1146

### CODE REVIEW

File: spanner/spanner_snippets/snippet_test.go [hunk 1]
```diff
@@ -239,6 +238,9 @@ func TestSample(t *testing.T) {
 	out = runCommand(t, "querywithstring", dbName)
 	assertContains(t, out, "42 Venue 42")
 
+	// Wait 5 seconds to avoid a time drift issue for the
+	// next query.
```
Comment (tbpg) [inline spanner/spanner_snippets/snippet_test.go]: Would you mind linking to the issue in this comment? Would be nice to have the extra context.
