### PR TITLE
testing(run): increase retry delay for builds to reduce flakiness

### LINKED ISSUE #1925: run/testing: TestHelloworldService failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: dab96e425eff4744b00767c0d423ef08854e465e
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/33a18ab8-19cf-4cc0-b1d5-72b47e9b7960), [Sponge](http://sponge2/33a18ab8-19cf-4cc0-b1d5-72b47e9b7960)
status: failed
<details><summary>Test output</summary><br><pre>2021/01/31 18:12:54 Attempt #1: Running: operation [build container image] for service [logging-manual]...
2021/01/31 18:12:54 Attempt #1: Executing: operation [build container image] for service [logging-manual]: /tmp/google-cloud-sdk/bin/gcloud: --quiet beta builds submit --project golang-samples-tests-7 --tag gcr.io/golang-samples-tests-7/logging-manual:20210131-181254
2021/01/31 18:12:54 Attempt #1: Running: operation [build container image] for service [helloworld]...
2021/01/31 18:12:54 Attempt #1: Executing: operation [build container image] for service [helloworld]: /tmp/google-cloud-sdk/bin/gcloud: --quiet beta builds submit --project golang-samples-tests-7 --tag gcr.io/golang-samples-tests-7/helloworld:20210131-181254
    helloworld.e2e_test.go:35: service.Deploy "helloworld": gcloud: gcr.io/golang-samples-tests-7/helloworld:20210131-181254: "gcloudExec: operation [build container image] for service [helloworld]: gave up after 3 failed attempts"</pre></details>

### LINKED ISSUE #1934: run/testing: TestDiagramService failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: b78c894435edc3c5bcf625ee69cf81e531922a8a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/89c9b76e-59c5-4513-8235-641e203e18ce), [Sponge](http://sponge2/89c9b76e-59c5-4513-8235-641e203e18ce)
status: failed
<details><summary>Test output</summary><br><pre>2021/02/02 18:29:50 Attempt #1: Running: operation [build container image] for service [diagram]...
2021/02/02 18:29:50 Attempt #1: Executing: operation [build container image] for service [diagram]: /tmp/google-cloud-sdk/bin/gcloud: --quiet beta builds submit --project golang-samples-tests-9 --tag gcr.io/golang-samples-tests-9/diagram:20210202-182950
    system_package.e2e_test.go:32: service.Deploy "diagram": gcloud: gcr.io/golang-samples-tests-9/diagram:20210202-182950: "gcloudExec: operation [build container image] for service [diagram]: gave up after 3 failed attempts"</pre></details>

### LINKED ISSUE #1944: run/testing: TestGRPCPingService failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 7cc02421347a2ff75d542aed7df8101c6aa11fc0
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/5b099f77-e55c-4dfc-9781-d8e416eb55d7), [Sponge](http://sponge2/5b099f77-e55c-4dfc-9781-d8e416eb55d7)
status: failed
<details><summary>Test output</summary><br><pre>    grpc_ping.e2e_test.go:44: Service.Build "grpc-ping": gcloud: gcr.io/golang-samples-tests-6/grpc-ping:20210208-181315: "gcloudExec: operation [build container image] for service [grpc-ping]: gave up after 5 failed attempts"</pre></details>

### PR DESCRIPTION
**Pull request by grayside**
Fixes #1934 
Fixes #1925
Fixes #1944

This iteration of improvement was discussed in #1934.
https://github.com/GoogleCloudPlatform/golang-samples/issues/1934#issuecomment-776279586 had my thoughts on a more complicated solution that would allow shorter retry delays.

### CODE REVIEW

File: internal/cloudrunci/gcloud.go [hunk 1]
```diff
@@ -42,8 +42,13 @@ func gcloud(label string, cmd *exec.Cmd) ([]byte, error) {
 	var out []byte
 	var err error
 
+	delaySeconds := 2 * time.Second
+	if strings.Contains(label, "build container image") {
```
Comment (tbpg) [inline internal/cloudrunci/gcloud.go:46]: Where does this label come from? Seems like it could easily change?

Comment (grayside) [reply internal/cloudrunci/gcloud.go:46]: This is set in the cloudrunci Build function which is used to create all gcloud commands for gcloud builds submit. I think it's safe to use, though I'm happy to create a constant. It is simpler than parsing the command arguments.

**Review by tbpg — APPROVED** [review]
