### PR TITLE
fix(pubsub): update concurrency sample

### LINKED ISSUE #2194: pubsub/subscriptions: TestPullMsgsConcurrencyControl failed
Note: #2082 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 2a6361b94cd77803b9a581422bdd827814576975
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/21253d29-52b5-4bca-8c45-a655d35d784b), [Sponge](http://sponge2/21253d29-52b5-4bca-8c45-a655d35d784b)
status: failed
<details><summary>Test output</summary><br><pre>    subscription_test.go:350: pullMsgsConcurrencyControl got Received 0 messages
        
        want Received 5 messages</pre></details>

### PR DESCRIPTION
**Pull request by hongalex**
The concurrency sample before didn't show how to configure the number of message handlers (`MaxOutstandingMessages`). This PR adds that and adds retries to reduce flakiness, as well as increasing the total pull time to 30 seconds to match the Java sample.

Fixes #2194

### CODE REVIEW

**Comment by hongalex** [comment]
The diff in the test is actually much smaller (just wrapping everything in the retry helper).

File: pubsub/subscriptions/pull_concurrency.go [hunk 1]
```diff
@@ -40,12 +39,15 @@ func pullMsgsConcurrenyControl(w io.Writer, projectID, subID string) error {
...
 	// concurrency settings. Otherwise, NumGoroutines will be set to 1.
 	sub.ReceiveSettings.Synchronous = false
-	// NumGoroutines is the number of goroutines sub.Receive will spawn to pull
-	// messages concurrently.
-	sub.ReceiveSettings.NumGoroutines = runtime.NumCPU()
+	// NumGoroutines determines the number of goroutines sub.Receive will spawn to pull
+	// messages.
+	sub.ReceiveSettings.NumGoroutines = 16
+	// MaxOutstandingMessages limits the number of concurrent handlers of messages.
+	// In this case, up to 8 messages can be handled concurrently.
```
Comment (codyoss) [inline pubsub/subscriptions/pull_concurrency.go:46]: This is unacked messages right? If so maybe include that tidbit?

**Review by codyoss — APPROVED** [review]
LGTM, just one question
