### PR TITLE
securitycenter: fix broken ListAssets test, stop skipping tests

### LINKED ISSUE #1375: securitycenter/assets: TestListAllProjectAssetsAtTime failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 7a04f482acc08b6dfd3c720b4947185e5db5e8e6
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/dc63fb60-1caf-43cb-a66e-0d9ffd116c4a), [Sponge](http://sponge2/dc63fb60-1caf-43cb-a66e-0d9ffd116c4a)
status: failed

### PR DESCRIPTION
**Pull request by tdh911**
Should fix #1375

### CODE REVIEW

File: securitycenter/assets/assets_test.go [hunk 1]
```diff
@@ -217,7 +217,7 @@ func TestListAllProjectAssetsAtTime(t *testing.T) {
 	}
 
 	buf.Reset()
-	var somethingInstant = time.Date(2019, 3, 15, 0, 0, 0, 0, time.UTC)
+	var somethingInstant = time.Now()
```
Comment (tbpg) [inline securitycenter/assets/assets_test.go:220]: Please remove the skip above.
