### PR TITLE
test(firestore): Cleanup before creating new docs

### LINKED ISSUE #4564: firestore: TestVectorSearchDistanceResultFieldMasked failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 097e9c29a207c4c09daca607a40aa01497f06c72
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/3d173f43-cdf6-4fa7-8a80-919dab48ea66), [Sponge](http://sponge2/3d173f43-cdf6-4fa7-8a80-919dab48ea66)
status: failed

### PR DESCRIPTION
**Pull request by bhshkh**
## Description

Fixes #4564, #4584, #4537, #4583, #4587, #4707, #4629, #4587, #4562

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [x] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [x] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

File: firestore/query_multiple_inequality_test.go [hunk 1]
```diff
@@ -148,15 +150,25 @@ func TestMultipleInequalitiesQuery(t *testing.T) {
 			Fields:     adminPbIndexFields,
 		},
 	}
+	var createdIndex *adminpb.Index
+	var waitErr error
```
Comment (telpirion) [inline firestore/query_multiple_inequality_test.go:154]: nit: I don't think you need to declare the `waitErr` here, since it's only used in the else block below.

**Review by telpirion — APPROVED** [review]
