### PR TITLE
test(spanner): unflake backup sample tests

### LINKED ISSUE #1900: spanner/spanner_snippets/spanner: TestBackupSample failed
Note: #1856 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: ee6aa086d41864d841c1e812b7ca324c9791795e
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/7fcf8c02-aa4f-4a39-a01b-41617fd6f26e), [Sponge](http://sponge2/7fcf8c02-aa4f-4a39-a01b-41617fd6f26e)
status: failed
<details><summary>Test output</summary><br><pre>    integration_test.go:384: failed to restore a backup: rpc error: code = FailedPrecondition desc = Cannot restore database (projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610790968-554a3bc7) because the maximum number of pending restores (1) for the instance (projects/golang-samples-tests/instances/golang-samples-tests) has been reached. Please retry the operation once the pending restores complete.
    integration_test.go:360: got output ""; want it to contain "Source database projects/golang-samples-tests/instances/golang-samples-tests/databases/smpl-1610790968-554a3bc7 restored from backup"
    integration_test.go:364: got output "Database projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610735832-ef74a5ce restored from backup is 100% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610733553-076379f7 restored from backup is 100% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610649534-02106cc1 restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610647094-c82d4836 restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610564514-958ff48c restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610476177-9dc56d36 restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610474301-80e242fc restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610390138-42f23917 restored from backup is 100% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610387794-8aa13ccf restored from backup is 100% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610303484-1a31bed1 restored from backup is 100% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610301137-8aa96a18 restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610216947-be6887a5 restored from backup is 0% optimized.\nDatabase projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610214744-dc936677 restored from backup is 0% optimized.\n"; want it to contain "Database projects/golang-samples-tests/instances/golang-samples-tests/databases/restore-1610790968-554a3bc7 restored from backup"</pre></details>

### PR DESCRIPTION
**Pull request by olavloite**
Cloud Spanner supports max 1 restore operation at any time on one instance. This can cause problems on test instances if multiple tests are running at the same time. This change adds a retry loop for the specific error that occurs if multiple restore operations are running at the same time.

The same retry loop was also [previously added for Java](https://github.com/googleapis/java-spanner/blob/2c745f31288d5f6ad501b5542ea01db72e015d1e/samples/snippets/src/test/java/com/example/spanner/SpannerSampleIT.java#L347) where the same problem also sometimes occurred.

Fixes #1900

### CODE REVIEW

File: spanner/spanner_snippets/spanner/integration_test.go [hunk 1]
```diff
@@ -380,8 +382,20 @@ func runSample(t *testing.T, f sampleFunc, dbName, errMsg string) string {
 
 func runBackupSample(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg string) string {
 	var b bytes.Buffer
-	if err := f(&b, dbName, backupID); err != nil {
-		t.Errorf("%s: %v", errMsg, err)
+	attempts := 0
```
Comment (tbpg) [inline spanner/spanner_snippets/spanner/integration_test.go:385]: Please use `testutil.Retry`.

**Review by tbpg — CHANGES_REQUESTED** [review]

File: spanner/spanner_snippets/spanner/integration_test.go (hunk 1 above)
Comment (olavloite) [reply spanner/spanner_snippets/spanner/integration_test.go]: Good point, I didn't know about the existence of that one.

File: spanner/spanner_snippets/spanner/integration_test.go [hunk 2]
```diff
@@ -386,6 +388,27 @@ func runBackupSample(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg
...
+				testError = err
+			}
+		}
+	})
+	if !success {
+		t.Errorf("%s: %v", errMsg, "backup test failed because it exceeded max attempts")
+	}
+	if testError != nil {
+		t.Errorf("%s: %v", errMsg, testError)
+	}
```
Comment (tbpg) [inline spanner/spanner_snippets/spanner/integration_test.go:408]: No need to do this. You can use `r.Errorf` instead of `r.Fail` whenever an error happens that you want to fail the retry attempt. If you get an error on every attempt, the test will fail with the right message.

Comment (olavloite) [reply spanner/spanner_snippets/spanner/integration_test.go]: @tbpg 
Thanks, that seems reasonable. But what is missing here AFICT is a feature that enables us to break the retry loop when the function returns an error that we don't want to retry. In this specific case only certain errors should be retried. Other errors should preferably fail the test immediately. I've added a feature for that to the test retryer for that. Would you mind taking a look?

File: spanner/spanner_snippets/spanner/integration_test.go [hunk 3]
```diff
@@ -386,6 +388,23 @@ func runBackupSample(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg
...
 }
 
+func runBackupSampleWithRetry(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg string, maxAttempts int) string {
+	var b bytes.Buffer
+	success := testutil.Retry(t, maxAttempts, time.Minute, func(r *testutil.R) {
+		if err := f(&b, dbName, backupID); err != nil {
+			if spanner.ErrCode(err) == codes.InvalidArgument && strings.Contains(err.Error(), "Please retry the operation once the pending restores complete") {
+				r.Errorf("%s: %v", errMsg, err)
+			} else {
+				r.FailNowf("%s: %v", errMsg, err)
```
Comment (tbpg) [inline spanner/spanner_snippets/spanner/integration_test.go:398]: Any particular reason we can't use `t.Fatalf` here? Do the retries matter at this point?

Comment (tbpg) [reply spanner/spanner_snippets/spanner/integration_test.go:398]: I tested out that `t.Fatalf` does the right thing with the following test:
```go
func TestFoo(t *testing.T) {
	testutil.Retry(t, 5, 100*time.Millisecond, func(r *testutil.R) {
		t.Logf("Attempt: %v", r.Attempt)
		if r.Attempt == 4 {
			t.Fatalf("The 4th attempt failed!")
		}
		r.Errorf("Failure! %v", r.Attempt)
	})
}
```

The output is:
```
=== RUN   TestFoo
    license_test.go:95: Attempt: 1
    license_test.go:95: Attempt: 2
    license_test.go:95: Attempt: 3
    license_test.go:95: Attempt: 4
    license_test.go:97: The 4th attempt failed!
--- FAIL: TestFoo (0.30s)
```

Comment (olavloite) [reply spanner/spanner_snippets/spanner/integration_test.go]: Argh. You're completely right, I don't know what I was thinking there. I've changed it into simply using `t.Fatalf`. Thanks for pointing it out.

File: spanner/spanner_snippets/spanner/integration_test.go [hunk 4]
```diff
@@ -386,6 +388,23 @@ func runBackupSample(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg
 	return b.String()
 }
 
+func runBackupSampleWithRetry(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg string, maxAttempts int) string {
+	var b bytes.Buffer
+	success := testutil.Retry(t, maxAttempts, time.Minute, func(r *testutil.R) {
+		if err := f(&b, dbName, backupID); err != nil {
```
Comment (tbpg) [inline spanner/spanner_snippets/spanner/integration_test.go:394]: Might want to call `b.Reset` at the start of every retry attempt.

File: spanner/spanner_snippets/spanner/integration_test.go [hunk 5]
```diff
@@ -386,6 +388,23 @@ func runBackupSample(t *testing.T, f backupSampleFunc, dbName, backupID, errMsg
...
+			if spanner.ErrCode(err) == codes.InvalidArgument && strings.Contains(err.Error(), "Please retry the operation once the pending restores complete") {
+				r.Errorf("%s: %v", errMsg, err)
+			} else {
+				t.Fatalf("%s: %v", errMsg, err)
+			}
+		}
+	})
+	if !success {
+		t.Errorf("%s: %v", errMsg, "backup test failed because it exceeded max attempts or was stopped")
+	}
```
Comment (tbpg) [inline spanner/spanner_snippets/spanner/integration_test.go:404]: You can delete this now.

**Review by tbpg — APPROVED** [review]
A couple comments, otherwise LGTM.

File: spanner/spanner_snippets/spanner/integration_test.go (hunk 4 above)
Comment (olavloite) [reply spanner/spanner_snippets/spanner/integration_test.go:395]: Good point, done.

File: spanner/spanner_snippets/spanner/integration_test.go (hunk 5 above)
Comment (olavloite) [reply spanner/spanner_snippets/spanner/integration_test.go]: Done.

**Review by tbpg — APPROVED** [review]
