### PR TITLE
test(storage): unflake TestGetKey

### LINKED ISSUE #2037: storage/service_account/hmac: TestGetKey failed
Note: #1985 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 8106ae9058e916342aa0a1e376a7729d429ec1b9
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/7dbcc9c1-10cd-4ae9-b5f0-dbc7bd29754c), [Sponge](http://sponge2/7dbcc9c1-10cd-4ae9-b5f0-dbc7bd29754c)
status: failed
<details><summary>Test output</summary><br><pre>panic: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/testing/testing.go:792 +0x387
/usr/local/go/src/runtime/panic.go:513 +0x1b9
/tmpfs/src/github/golang-samples/storage/service_account/hmac/hmac_test.go:129 +0x36
/tmpfs/src/github/golang-samples/internal/testutil/retry.go:34 +0xc3
/tmpfs/src/github/golang-samples/storage/service_account/hmac/hmac_test.go:128 +0x161
/usr/local/go/src/testing/testing.go:827 +0xbf
/usr/local/go/src/testing/testing.go:878 +0x35c</pre></details>

### PR DESCRIPTION
**Pull request by danielduhh**
Fixes #2037 by adding retry logic for unit test key generation. ~~Also replaced deferred failures (`Errorf`) with FailNow (`Fatalf`)~~

### CODE REVIEW

File: storage/service_account/hmac/hmac_test.go [hunk 1]
```diff
@@ -119,21 +119,22 @@ func TestDeactivateKey(t *testing.T) {
...
+		if key == nil {
+			t.Fatalf("Returned nil key.")
+		}
+
 		key, err = getHMACKey(ioutil.Discard, key.AccessID, key.ProjectID)
 		if err != nil {
 			r.Errorf("Error in getHMACKey: %s", err)
 			return
 		}
-		if key == nil {
```
Comment (tritone) [inline storage/service_account/hmac/hmac_test.go:134]: You should leave this check here -- it's important to check that the sample successfully retrieved a key as well.

File: storage/service_account/hmac/hmac_test.go [hunk 2]
```diff
@@ -119,21 +119,22 @@ func TestDeactivateKey(t *testing.T) {
...
-	}
-
 	testutil.Retry(t, 10, 10*time.Second, func(r *testutil.R) {
+		key, err := createTestKey(tc.ProjectID)
+		defer deleteTestKey(key)
+		if err != nil {
+			t.Fatalf("Error in key creation: %s", err)
+		}
+
+		if key == nil {
```
Comment (tritone) [inline storage/service_account/hmac/hmac_test.go:129]: Add a comment that this case should not be possible, but we added it based on earlier failures.

**Review by tritone — COMMENTED** [review]
thanks!

File: storage/service_account/hmac/hmac_test.go [hunk 3]
```diff
@@ -119,21 +119,22 @@ func TestDeactivateKey(t *testing.T) {
...
-	defer deleteTestKey(key)
-	if err != nil {
-		t.Errorf("Error in key creation: %s", err)
-	}
-
 	testutil.Retry(t, 10, 10*time.Second, func(r *testutil.R) {
+		key, err := createTestKey(tc.ProjectID)
+		defer deleteTestKey(key)
+		if err != nil {
+			t.Fatalf("Error in key creation: %s", err)
```
Comment (tritone) [inline storage/service_account/hmac/hmac_test.go:126]: This and L130 should be `r.Fatalf` rather than `t` to use the retry correctly

Comment (danielduhh) [reply storage/service_account/hmac/hmac_test.go:126]: Doesn't look like the sample testutil supports  `Fatalf` (just `Errorf` & `Logf` functions)

File: storage/service_account/hmac/hmac_test.go (hunk 2 above)
Comment (tbpg) [reply storage/service_account/hmac/hmac_test.go:131]: This should also be `r.Errorf` followed by `return`.

File: storage/service_account/hmac/hmac_test.go [hunk 4]
```diff
@@ -162,13 +162,25 @@ func TestDeleteKey(t *testing.T) {
...
-		return nil, fmt.Errorf("storage.NewClient: %v", err)
-	}
-	return key, nil
+	var key *storage.HMACKey
+	var err error
+
+	testutil.Retry(t, 10, 10*time.Second, func(r *testutil.R) {
+		key, err = storageClient.CreateHMACKey(ctx, projectID, serviceAccountEmail)
+		if err != nil {
+			t.Fatalf("Error in CreateHMACKey: %v", err)
```
Comment (tritone) [inline storage/service_account/hmac/hmac_test.go:173]: As @tbpg said, this and L178 should be `r.Errorf`. Otherwise the retry will not work.

Comment (danielduhh) [reply storage/service_account/hmac/hmac_test.go]: yep, just fixed this in latest commit

**Review by tritone — APPROVED** [review]

File: storage/service_account/hmac/hmac_test.go [hunk 5]
```diff
@@ -79,7 +79,7 @@ func TestCreateKey(t *testing.T) {
 
 func TestActivateKey(t *testing.T) {
 	tc := testutil.SystemTest(t)
-	key, err := createTestKey(tc.ProjectID)
+	key, err := createTestKey(tc.ProjectID, t)
 	defer deleteTestKey(key)
 	if err != nil {
 		t.Errorf("Error in key creation: %s", err)
```
Comment (tbpg) [inline storage/service_account/hmac/hmac_test.go:85]: This (and all similar checks for `createTestKey`) should probably be `t.Fatalf`. If key creation failed, I don't think it makes sense to continue?

(`t.Fatalf` ends the test immediately. `t.Errorf` continues execution.)

Comment (danielduhh) [reply storage/service_account/hmac/hmac_test.go:85]: I thought about that (failing immediately in the createTestKey function)..  @tritone mentioned we could probably just leave it as is since the key creation step is just a setup for the sample tests

**Review by tbpg — APPROVED** [review]
