### PR TITLE
fix: add NUMERIC column to sample

### LINKED ISSUE #1942: spanner: spanner_create_table_with_datatypes does not include NUMERIC
The `spanner_create_table_with_datatypes` sample does not include a `NUMERIC` column.

### PR DESCRIPTION
**Pull request by olavloite**
Adds the missing `NUMERIC` column to the sample table.

Fixes #1942

### CODE REVIEW

File: spanner/spanner_snippets/spanner/spanner_create_table_with_datatypes.go [hunk 1]
```diff
@@ -47,6 +47,7 @@ func createTableWithDatatypes(w io.Writer, db string) error {
 				LastContactDate DATE,
 				OutdoorVenue BOOL,
 				PopularityScore FLOAT64,
+				Revenue NUMERIC,
```
Comment (tbpg) [inline spanner/spanner_snippets/spanner/spanner_create_table_with_datatypes.go:50]: Test failure:
```
integration_test.go:378: failed to add numeric column: rpc error: code = FailedPrecondition desc = Duplicate column name Venues.Revenue.
```

**Review by tbpg — CHANGES_REQUESTED** [review]

File: spanner/spanner_snippets/spanner/spanner_create_table_with_datatypes.go (hunk 1 above)
Comment (olavloite) [reply spanner/spanner_snippets/spanner/spanner_create_table_with_datatypes.go:50]: The test failure has been fixed. It was caused by a different sample that adds the column, and that sample is also being executed as part of the integration tests.

**Review by skuruppu — APPROVED** [review]

**Review by tbpg — APPROVED** [review]
