### PR TITLE
test(spanner): increase timeout and cleanup test

### LINKED ISSUE #1726: spanner/spanner_leaderboard: TestSample failed
Note: #1387 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: c158606d8f33158632f65cfc75190b78a1cbe616
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/b5bd3fe8-d818-442c-8d2b-143853fa04e1), [Sponge](http://sponge2/b5bd3fe8-d818-442c-8d2b-143853fa04e1)
status: failed
<details><summary>Test output</summary><br><pre>    leaderboard_test.go:92: run("insertscores", "projects/golang-samples-tests/instances/golang-samples-tests/databases/test-l-golang-samples-tests-3"): spanner: code = "DeadlineExceeded", desc = "Deadline Exceeded"
    leaderboard_test.go:58: got output "insertscores failed with spanner: code = \"DeadlineExceeded\", desc = \"Deadline Exceeded\""; want it to contain "Inserted scores"
    leaderboard_test.go:93: run("insertscores", "projects/golang-samples-tests/instances/golang-samples-tests/databases/test-l-golang-samples-tests-3"): spanner: code = "DeadlineExceeded", desc = "Deadline Exceeded"
    leaderboard_test.go:58: got output "insertscores failed with spanner: code = \"DeadlineExceeded\", desc = \"Deadline Exceeded\""; want it to contain "Inserted scores"
    leaderboard_test.go:58: got output ""; want it to contain "PlayerId: "
    leaderboard_test.go:58: got output ""; want it to contain "PlayerId: "
    leaderboard_test.go:58: got output ""; want it to contain "PlayerId: "
    leaderboard_test.go:58: got output ""; want it to contain "PlayerId: "</pre></details>

### PR DESCRIPTION
**Pull request by olavloite**
Inserting 800 rows as a single Batch DML statement can take a long time, and the transaction can be aborted one or more times. The deadline used for such an operation therefore needs to be (very) long. It is now increased to 10 minutes.

Furthermore, the test case has been cleaned up a little bit:
* The multiple deferred functions for cleaning up have been combined into one.
* The database name is no longer fixed, allowing multiple instances of this test case to be executed at the same time.
* The generated player id's are now guaranteed to be unique. The previous version generated random id values that could overlap (although the probability was extremely low).

Fixes #1726

### CODE REVIEW

File: spanner/spanner_leaderboard/leaderboard.go [hunk 1]
```diff
@@ -94,15 +114,16 @@ func insertPlayers(ctx context.Context, w io.Writer, client *spanner.Client) err
...
+	min := int64(1000000000)
+	max := int64(9000000000)
+	rnd := newUniqueRand()
 	// Insert 100 player records into the Players table
 	_, err = client.ReadWriteTransaction(ctx, func(ctx context.Context, txn *spanner.ReadWriteTransaction) error {
 		stmts := []spanner.Statement{}
 		for i := 1; i <= 100; i++ {
 			numberOfPlayers++
-			playerID := rand.Intn(max-min) + min
+			playerID := rnd.rnd(min, max)
```
Comment (tbpg) [inline spanner/spanner_leaderboard/leaderboard.go:125]: Does the player ID need to be an int? Can we use a UUID instead?

File: spanner/spanner_leaderboard/leaderboard_test.go [hunk 2]
```diff
@@ -61,8 +74,8 @@ func TestSample(t *testing.T) {
 	runCommand := func(t *testing.T, cmd string, dbName string, timespan int) string {
 		t.Helper()
 		var b bytes.Buffer
-		// Set timeout to 60s so it should avoid DeadlineExceeded error.
-		cctx, cancel := context.WithTimeout(ctx, 60000*time.Millisecond)
+		// Set timeout to 600 seconds so it should avoid DeadlineExceeded error.
+		cctx, cancel := context.WithTimeout(ctx, 600*time.Second)
```
Comment (tbpg) [inline spanner/spanner_leaderboard/leaderboard_test.go:78]: Can we insert fewer rows into the table to speed it up? I _think_ this is only used in a Codelab. So, I'm willing to have a less-robust test for the sake of reliability and speed.

**Review by tbpg — CHANGES_REQUESTED** [review]
Thank you for cleaning this up!

File: spanner/spanner_leaderboard/leaderboard.go (hunk 1 above)
Comment (olavloite) [reply spanner/spanner_leaderboard/leaderboard.go:125]: I don't think we should change that. This sample is used across all supported programming languages and uses the same data model for all of them.

File: spanner/spanner_leaderboard/leaderboard_test.go (hunk 2 above)
Comment (olavloite) [reply spanner/spanner_leaderboard/leaderboard_test.go:78]: I noticed that the test case is executing the `insertPlayers` and `insertScores` twice. AFAICT, there's no good reason for doing so, and reducing that to once for both methods will significantly reduce the total number of rows that are inserted (from 1600 to 400 for scores and from 200 to 100 for players). That should speed it up quite a bit.

The 10 minutes should be overkill in most cases. It seems that the deadline is most commonly exceeded if Spanner aborts the transaction a couple of times in a row, causing multiple retries.

**Review by tbpg — APPROVED** [review]
