### PR TITLE
test(firestore): add retry to flaky listen test

### LINKED ISSUE #1978: firestore/firestore_snippets: TestListenChanges failed
Note: #1759 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 8b3112eeacc3fc33ab0f3eec699f9cbf4a3c61ed
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/fe341d13-dc55-48d4-b150-8aa19cce856b), [Sponge](http://sponge2/fe341d13-dc55-48d4-b150-8aa19cce856b)
status: failed
<details><summary>Test output</summary><br><pre>listen_test.go:125: listenChanges got
    ----
    New city: map[state:CA name:Los Angeles]
    New city: map[name:San Francisco state:CA]
    
    ----
    Want to contain:
    ----
    population:3900000
    ----</pre></details>

### PR DESCRIPTION
**Pull request by crwilcox**
Wrap listen tests in retry. 

Fixes #1978

### CODE REVIEW

File: firestore/firestore_snippets/listen_test.go [hunk 1]
```diff
@@ -101,29 +101,31 @@ func TestListenChanges(t *testing.T) {
...
+			err := listenChanges(ctx, buf, projectID, collection)
+			if err != nil {
+				r.Errorf("listenChanges: %v", err)
+			}
+			c <- buf
+		}()
+		// Add some changes to data in parallel.
+		time.Sleep(time.Second)
+		var pop int64 = 3900000
+		if _, err := client.Collection(collection).Doc("LA").Update(ctx, []firestore.Update{
```
Comment (tritone) [inline firestore/firestore_snippets/listen_test.go:118]: Is there anything stateful about this? That is, if you run the test twice, will the change look the same on the listener end both times? Just wanted to confirm.

Comment (crwilcox) [reply firestore/firestore_snippets/listen_test.go:118]: Listeners report on changes since listener start. so starting the func to listen, then updating the document, should result in an update containing population. This should happen pretty rapidly.

It is possible that we also could add a delay before line 125, ensuring that the listener had a chance to observe the data update.

in essence, I think I may be able to scope to just ln123-128

Comment (crwilcox) [reply firestore/firestore_snippets/listen_test.go]: After further thought I am fairly sure the issue is `<-c` is unblocking due to reading the initial state, not also including changes (update events). We can retry the reading of the buffer a couple of times to ensure we are in a steady state.

**Review by tritone — APPROVED** [review]

**Review by codyoss — APPROVED** [review]
