### PR TITLE
test(firestore): extend duration before timeout on TestListenChanges

### LINKED ISSUE #2425: firestore: TestListenChanges failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/main/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 3e54bd98cab04bfd493505d07d573e8a11c5335d
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/a179a5c4-c35f-4414-a83c-dc94323c71cd), [Sponge](http://sponge2/a179a5c4-c35f-4414-a83c-dc94323c71cd)
status: failed

### PR DESCRIPTION
**Pull request by telpirion**
Fixes #2425

### CODE REVIEW

File: firestore/listen_test.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ import (
 	"github.com/GoogleCloudPlatform/golang-samples/internal/testutil"
 )
 
-var duration time.Duration = 15 * time.Second
+var duration time.Duration = 20 * time.Second
```
Comment (enocom) [inline firestore/listen_test.go:31]: nit:

``` golang
var duration = 20 * time.Second
```

**Review by enocom — APPROVED** [review]

File: firestore/listen_test.go (hunk 1 above)
Comment (telpirion) [reply firestore/listen_test.go]: Done.
