### PR TITLE
internal/testutil: get absolute filepath

### LINKED ISSUE #1103: internal/e2e: GAE E2E tests failing
```
--- FAIL: TestGo11xStatic (0.08s)
    standard_test.go:62: could not deploy static: could not read service: open github.com/GoogleCloudPlatform/golang-samples/appengine/go11x/static/app.yaml: no such file or directory
--- FAIL: TestHelloWorld (0.08s)
    standard_test.go:62: could not deploy hw: could not read service: open github.com/GoogleCloudPlatform/golang-samples/appengine/go11x/helloworld/app.yaml: no such file or directory
FAIL
FAIL	github.com/GoogleCloudPlatform/golang-samples/internal/e2e	0.168s
```

### PR DESCRIPTION
**Pull request by tbpg**
Fixes #1103.

### CODE REVIEW

File: internal/testutil/testutil.go [hunk 1]
```diff
@@ -89,11 +90,22 @@ func testContext() (Context, error) {
...
+	cfg := &packages.Config{
+		Mode:  packages.NeedName | packages.NeedFiles,
+		Tests: true,
+	}
+	pkgs, err := packages.Load(cfg, "github.com/GoogleCloudPlatform/golang-samples")
 	if err != nil {
-		return tc, fmt.Errorf("Could not find golang-samples: %v", err)
+		return tc, fmt.Errorf("could not find golang-samples: %v", err)
+	}
+	for _, pkg := range pkgs {
```
Comment (grayside) [inline internal/testutil/testutil.go]: Given we expect `pkgs` to always be a slice of one package, is the loop best practice vs. just checking the first element? Or perhaps I've misunderstood what `packages.Load` might do?

File: internal/testutil/testutil.go [hunk 2]
```diff
@@ -89,11 +90,22 @@ func testContext() (Context, error) {
...
+		if len(pkg.GoFiles) > 0 && strings.HasSuffix(pkg.GoFiles[0], ".go") {
```
Comment (grayside) [inline internal/testutil/testutil.go]: Which other kinds of files does this categorize as GoFiles?

File: internal/testutil/testutil.go [hunk 3]
```diff
@@ -89,11 +90,22 @@ func testContext() (Context, error) {
...
+			tc.Dir = filepath.Dir(pkg.GoFiles[0])
```
Comment (grayside) [inline internal/testutil/testutil.go]: So the problem with the current code is that instead of getting the path of the golang-samples directory we need the path to the first file? I'm not clear why this is needed, a code comment would be useful for future reference.

File: internal/testutil/testutil.go (hunk 1 above)
Comment (tbpg) [reply internal/testutil/testutil.go]: Added a comment. It returns multiple packages (`foo`, `foo.test`, and another `foo`?)

File: internal/testutil/testutil.go (hunk 2 above)
Comment (tbpg) [reply internal/testutil/testutil.go]: There is one package with a file without the `.go` extension.

File: internal/testutil/testutil.go (hunk 3 above)
Comment (tbpg) [reply internal/testutil/testutil.go]: The file is in the package, which is in the root of the repo. So, if we get the `Dir` of that file, it will be the directory of the package. I hope that makes sense.

Comment (grayside) [reply internal/testutil/testutil.go]: But why is that different from the PkgPath?

Comment (tbpg) [reply internal/testutil/testutil.go]: `PkgPath` is the Go package path (`github.com/GoogleCloudPlatform/golang-samples`). This is getting the file path (`/home/.../golang-samples`).

**Comment by tbpg** [comment]
Going to merge TBR to hopefully get the build green before the holiday.
