### PR TITLE
fix(run): deflake sigterm-handler by sigterm'ing explicitly

### LINKED ISSUE #2444: run/testing: TestSigtermHandlerService failed
Note: #2042 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: c732e8f9ceebeaab0493c0a8b574588f38071196
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/ca1df97e-b278-4fdc-b03e-95455d8c8a31), [Sponge](http://sponge2/ca1df97e-b278-4fdc-b03e-95455d8c8a31)
status: failed
<details><summary>Test output</summary><br><pre>    sigterm_handler.e2e_test.go:33: service.Deploy "sigterm-handler": gcloud: gcr.io/golang-samples-tests-2/sigterm-handler:20220217-190901: "gcloudExec: operation [build container image] for service [sigterm-handler]: gave up after 5 failed attempts"</pre></details>

### PR DESCRIPTION
**Pull request by muncus**
Using a query param, request explicit termination, rather than waiting for
instance timeouts.

Fixes #2444

This PR also increases a client Timeout that was causing some flakiness (like
[this
one](https://source.cloud.google.com/results/invocations/a3483248-ddbc-44db-b4b8-e8a6f453a55b/targets/github%2Fgolang-samples%2Frun%2Ftesting/tests))

### CODE REVIEW

File: run/sigterm-handler/main.go [hunk 1]
```diff
@@ -27,6 +27,8 @@ import (
 	"time"
 )
 
+var SignalChan chan (os.Signal)
```
Comment (enocom) [inline run/sigterm-handler/main.go:30]: Since this is in the `main` package, this shouldn't be exported.

File: run/testing/sigterm_handler.e2e_test.go [hunk 2]
```diff
@@ -64,7 +65,7 @@ func GetLogEntries(service *cloudrunci.Service, t *testing.T) {
 	attempts := 6
 	found, err := service.LogEntries(filter, find, attempts)
 	if err != nil || !found {
-		t.Errorf("%q log entry not found.", find)
+		t.Errorf("%q log entry not found. (%s)", find, err)
```
Comment (enocom) [inline run/testing/sigterm_handler.e2e_test.go:68]: %v is preferred by convention here.

File: run/testing/sigterm_handler.e2e_test.go [hunk 3]
```diff
@@ -35,19 +35,20 @@ func TestSigtermHandlerService(t *testing.T) {
...
 
-	client := http.Client{Timeout: 10 * time.Second}
+	client := http.Client{Timeout: 30 * time.Second}
 	resp, err := client.Do(req)
 	if err != nil {
 		t.Fatalf("client.Do: %v", err)
 	}
-	defer resp.Body.Close()
 	fmt.Printf("client.Do: %s %s\n", req.Method, req.URL)
+	resp.Body.Close()
```
Comment (enocom) [inline run/testing/sigterm_handler.e2e_test.go:51]: What's the reasoning for this change?

File: run/sigterm-handler/main.go [hunk 4]
```diff
@@ -75,5 +77,10 @@ func main() {
 // [END cloudrun_sigterm_handler]
 
 func handler(w http.ResponseWriter, r *http.Request) {
-	fmt.Fprint(w, "Hello World!\n")
+	if r.URL.Query().Get("terminate") != "" {
+		SignalChan <- syscall.SIGTERM
+		fmt.Fprint(w, "Goodbye World!\n")
+	} else {
```
Comment (enocom) [inline run/sigterm-handler/main.go:83]: Instead of `else`, an early return is more Go-like.

File: run/sigterm-handler/main.go (hunk 1 above)
Comment (enocom) [reply run/sigterm-handler/main.go:30]: Also, why not initialize the chan here as well?

**Review by enocom — CHANGES_REQUESTED** [review]

File: run/sigterm-handler/main.go [hunk 5]
```diff
@@ -75,5 +77,10 @@ func main() {
 // [END cloudrun_sigterm_handler]
 
 func handler(w http.ResponseWriter, r *http.Request) {
-	fmt.Fprint(w, "Hello World!\n")
+	if r.URL.Query().Get("terminate") != "" {
```
Comment (averikitsch) [inline run/sigterm-handler/main.go:80]: Please add a note that this is for testing purposes

Comment (muncus) [reply run/sigterm-handler/main.go:80]: Done.

File: run/testing/sigterm_handler.e2e_test.go (hunk 3 above)
Comment (muncus) [reply run/testing/sigterm_handler.e2e_test.go]: This was a mistake, and i've restored the defer.
Previously, i was issuing 2 requests, and wanted to ensure Body was closed before proceeding.

File: run/sigterm-handler/main.go (hunk 1 above)
Comment (muncus) [reply run/sigterm-handler/main.go]: Fixed, on both counts.

**Review by enocom — APPROVED** [review]

File: run/sigterm-handler/main.go [hunk 6]
```diff
@@ -75,5 +76,11 @@ func main() {
 // [END cloudrun_sigterm_handler]
 
 func handler(w http.ResponseWriter, r *http.Request) {
+	// The 'terminate' parameter is used by tests in sigterm_handler.e2e_test.go
+	if r.URL.Query().Get("terminate") != "" {
+		signalChan <- syscall.SIGTERM
+		fmt.Fprint(w, "Goodbye World!\n")
```
[the remark this answers is not in the document]
Comment (muncus) [reply run/sigterm-handler/main.go:82]: Good call. I'll fix before submitting.
