### PR TITLE
fix(storage): fix TestListenChanges flakey test

### LINKED ISSUE #1759: firestore/firestore_snippets: TestListenChanges failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: ae6c8fa9115c91be5f54bcb162e3bd014eac5d05
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/9255b763-517f-4701-a697-0e8e31eadb46), [Sponge](http://sponge2/9255b763-517f-4701-a697-0e8e31eadb46)
status: failed
<details><summary>Test output</summary><br><pre>listen_test.go:125: listenChanges got
    ----
    New city: map[name:Los Angeles state:CA]
    New city: map[state:CA name:San Francisco]
    
    ----
    Want to contain:
    ----
    population:3900000
    ----</pre></details>

### PR DESCRIPTION
**Pull request by AlisskaPie**
Fixes #1759

### CODE REVIEW

**Comment by AlisskaPie** [comment]
@tritone could you take a look, please? Thanks in advance! :)

File: firestore/firestore_snippets/listen_test.go [hunk 1]
```diff
@@ -114,11 +113,14 @@ func TestListenChanges(t *testing.T) {
 	// Add some changes to data in parallel.
 	time.Sleep(time.Second)
 	var pop int64 = 3900000
-	if _, err := client.Collection(collection).Doc("LA").Update(ctx, []firestore.Update{
-		{Path: "population", Value: pop},
-	}); err != nil {
-		log.Fatalf("Doc.Update: %v", err)
-	}
+
+	testutil.Retry(t, 10, 10*time.Second, func(r *testutil.R) {
```
Comment (tritone) [inline firestore/firestore_snippets/listen_test.go:117]: Looking at this more closely, I don't think this retry should be necessary since we were not seeing any failures in L120 previously, only at L125 (original line numbers). Increasing the timeout alone should probably be sufficient. Any thoughts @BenWhitehead @tbpg ?

File: firestore/firestore_snippets/listen_test.go [hunk 2]
```diff
@@ -98,7 +97,7 @@ func TestListenChanges(t *testing.T) {
 	client, projectID, collection := setup(ctx, t)
 	defer client.Close()
 
-	ctx, cancel := context.WithTimeout(ctx, duration)
+	ctx, cancel := context.WithTimeout(ctx, 15*time.Second)
```
Comment (tbpg) [inline firestore/firestore_snippets/listen_test.go:100]: Can we increase `duration`, rather than use a one-off value here?

File: firestore/firestore_snippets/listen_test.go (hunk 1 above)
Comment (tbpg) [reply firestore/firestore_snippets/listen_test.go:117]: +1 -- no need to add this retry if this isn't where the failure was.

**Review by tbpg — CHANGES_REQUESTED** [review]
Thank you!

File: firestore/firestore_snippets/listen_test.go (hunk 1 above)
Comment (AlisskaPie) [reply firestore/firestore_snippets/listen_test.go]: Ok, got it

**Review by AlisskaPie — COMMENTED** [review]
Thank you!

**Review by tritone — APPROVED** [review]

**Review by tbpg — APPROVED** [review]
Thanks!
