### PR TITLE
fix(run): Add retries to tests

### LINKED ISSUE #2106: run/testing: TestHTTP2Server failed
Note: #2027 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 9bc859f48ef701a4b81794b5bb86b509b17e2e4c
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/95c8c738-2c3d-4cd8-ba9a-e84e80c3f971), [Sponge](http://sponge2/95c8c738-2c3d-4cd8-ba9a-e84e80c3f971)
status: failed
<details><summary>Test output</summary><br><pre>2021/06/19 18:30:33 Attempt #1: Running: operation [build container image] for service [h2c]...
2021/06/19 18:30:33 Attempt #1: Executing: operation [build container image] for service [h2c]: /tmp/google-cloud-sdk/bin/gcloud: --quiet beta builds submit --project golang-samples-tests-6 --pack=image=gcr.io/golang-samples-tests-6/h2c:20210619-182730
2021/06/19 18:30:58 Attempt #1: Running: operation [deploy service] for service [logging-manual]...
2021/06/19 18:30:58 Attempt #1: Executing: operation [deploy service] for service [logging-manual]: /tmp/google-cloud-sdk/bin/gcloud: --quiet alpha run deploy logging-manual-20210619-182730 --project golang-samples-tests-6 --image gcr.io/golang-samples-tests-6/logging-manual:20210619-182730 --platform managed --region us-central1
2021/06/19 18:31:09 Attempt #1: Running: operation [get url] for service [logging-manual]...
2021/06/19 18:31:09 Attempt #1: Executing: operation [get url] for service [logging-manual]: /tmp/google-cloud-sdk/bin/gcloud: --quiet run services describe logging-manual-20210619-182730 --project golang-samples-tests-6 --format value(status.url) --platform managed --region us-central1
2021/06/19 18:31:09 Attempt #1: Running: operation [id-token]...
2021/06/19 18:31:09 Attempt #1: Executing: operation [id-token]: /tmp/google-cloud-sdk/bin/gcloud: --quiet auth print-identity-token
client.Do: POST https://logging-manual-20210619-182730-2pcfdjfgca-uc.a.run.app/
2021/06/19 18:31:10 Attempt #1: Running: operation [delete service] for service [logging-manual]...
2021/06/19 18:31:10 Attempt #1: Executing: operation [delete service] for service [logging-manual]: /tmp/google-cloud-sdk/bin/gcloud: --quiet run services delete logging-manual-20210619-182730 --project golang-samples-tests-6 --platform managed --region us-central1
2021/06/19 18:31:16 Attempt #1: Running: operation [delete container image] for service [logging-manual]...
2021/06/19 18:31:16 Attempt #1: Executing: operation [delete container image] for service [logging-manual]: /tmp/google-cloud-sdk/bin/gcloud: --quiet container images delete gcr.io/golang-samples-tests-6/logging-manual:20210619-182730
    h2c.e2e_test.go:59: http2.Get: unexpected response status: 403 Forbidden
2021/06/19 18:31:42 Attempt #1: Running: operation [delete service] for service [h2c]...
2021/06/19 18:31:42 Attempt #1: Executing: operation [delete service] for service [h2c]: /tmp/google-cloud-sdk/bin/gcloud: --quiet run services delete h2c-20210619-182730 --project golang-samples-tests-6 --platform managed --region us-central1
2021/06/19 18:31:48 Attempt #1: Running: operation [delete container image] for service [h2c]...
2021/06/19 18:31:48 Attempt #1: Executing: operation [delete container image] for service [h2c]: /tmp/google-cloud-sdk/bin/gcloud: --quiet container images delete gcr.io/golang-samples-tests-6/h2c:20210619-182730</pre></details>

### PR DESCRIPTION
**Pull request by averikitsch**
Fixes #2106

### CODE REVIEW

File: run/testing/h2c.e2e_test.go [hunk 1]
```diff
@@ -50,20 +51,22 @@ func TestHTTP2Server(t *testing.T) {
...
-	defer resp.Body.Close()
-	b, err := ioutil.ReadAll(resp.Body)
-	if err != nil {
-		t.Fatalf("resp.Body.Read failed: %v", err)
-	}
-	if expected, got := "This request is served over HTTP/2.0 protocol.", string(b); !strings.Contains(got, expected) {
-		t.Fatalf("response body doesn't contain %q; got=%q", expected, got)
-	}
+		if err != nil {
+			t.Fatalf("http2.Get failed: %v", err)
```
Comment (codyoss) [inline run/testing/h2c.e2e_test.go:58]: Please replace `t.` with `r.` in this function -- this is what enables retrying

**Review by codyoss — CHANGES_REQUESTED** [review]

**Review by grayside — APPROVED** [review]
