### PR TITLE
fix(compute/disks): don't fail tests in case of not found disks during deletion

### LINKED ISSUE #2929: compute/disks: TestComputeDisksSnippets failed
Note: #2677 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 82da276a923cb9f99534d6c9ee4e52f83839c88a
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/868e166c-5807-408b-85d3-e8e2c877d425), [Sponge](http://sponge2/868e166c-5807-408b-85d3-e8e2c877d425)
status: failed
<details><summary>Test output</summary><br><pre>    disks_test.go:274: resizeRegionalDisk got err: unable to delete disk: googleapi: Error 404: The resource 'projects/golang-samples-tests-2/regions/europe-central2/disks/test-disk-03-26-2023-3644037003058329927' was not found</pre></details>

### PR DESCRIPTION
**Pull request by rsamborski**
## Description

Fixes #2929

Don't fail tests in case there is a 404 error during disk deletion. Disk might have been removed already by the ripper or during VM deletion.

## Checklist
- [X] I have followed [Contributing Guidelines from CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md)
- [X] **Tests** pass:   `go test -v ./..` (see [Testing](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#testing))
- [X] **Code formatted**:   `gofmt` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [X] **Vetting** pass:   `go vet` (see [Formatting](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/CONTRIBUTING.md#formatting))
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by rsamborski** [comment]
@telpirion Please take another look. I have refactored the tests to make them independent from one another and secure resources from leaking.

File: compute/disks/disks_test.go [hunk 1]
```diff
@@ -146,38 +171,49 @@ func deleteInstance(ctx context.Context, projectId, zone, instanceName string) e
 
 	op, err := instancesClient.Delete(ctx, req)
 	if err != nil {
-		return err
+		t.Error("instanceClient.Delete err", err)
```
Comment (telpirion) [inline compute/disks/disks_test.go:174]: question: did you intend to use a formatting string here?

File: compute/disks/disks_test.go [hunk 2]
```diff
@@ -146,38 +171,49 @@ func deleteInstance(ctx context.Context, projectId, zone, instanceName string) e
...
 	}
 
-	return op.Wait(ctx)
+	err = op.Wait(ctx)
+	if err != nil {
+		t.Error("instanceClient.Delete err", err)
```
Comment (telpirion) [inline compute/disks/disks_test.go:179]: Same as above. I think this will print out the first string then the second string (without any space). Let's explicitly use a formatting string instead.

File: compute/disks/disks_test.go [hunk 3]
```diff
@@ -282,65 +311,62 @@ func TestComputeDisksSnippets(t *testing.T) {
...
-			t.Errorf("deleteDisk got err: %v", err)
-		}
 	})
 
 	t.Run("create, clone and delete an encrypted disk", func(t *testing.T) {
-		buf.Reset()
+		encDiskName1 := fmt.Sprintf("test-enc-disk1-%v-%v", time.Now().Format("01-02-2006"), r.Int())
+		sourceDisk := fmt.Sprintf("projects/%s/zones/europe-west2-b/disks/%s", tc.ProjectID, encDiskName1)
+		encDiskName2 := fmt.Sprintf("test-enc-disk2-%v-%v", time.Now().Format("01-02-2006"), r.Int())
+		buf := &bytes.Buffer{}
```
Comment (telpirion) [inline compute/disks/disks_test.go:350]: issue: declare an empty buffer like so:

```
var *bytes.Buffer
```

File: compute/disks/disks_test.go [hunk 4]
```diff
@@ -388,26 +416,28 @@ func TestComputeDisksSnippets(t *testing.T) {
...
 				foundDisk = true
 			}
 		}
 		if !foundDisk {
-			t.Errorf("The disk %s is not attached to the instance!", instanceDiskName2)
+			t.Errorf("The disk %s is not attached to the instance!", instanceRegionalDiskName)
 		}
 
-		// cannot clean up the disk just yet because it must be done after the VM is terminated
+		// cannot clean up the disk just yet because it must be done after the VM is terminated - will be done in deleteInstance function
```
Comment (telpirion) [inline compute/disks/disks_test.go:427]: issue: insert line break. This comment is too long for a single line.

File: compute/disks/disks_test.go [hunk 5]
```diff
@@ -423,37 +453,14 @@ func TestComputeDisksSnippets(t *testing.T) {
...
 				foundDisk = true
 			}
 		}
 		if !foundDisk {
-			t.Errorf("The disk %s is not attached to the instance!", instanceDiskName3)
+			t.Errorf("The disk %s is not attached to the instance!", instanceRegionalDiskName)
 		}
 
-		// cannot clean up the disk just yet because it must be done after the VM is terminated
+		// cannot clean up the disk just yet because it must be done after the VM is terminated - will be done in deleteInstance function
```
Comment (telpirion) [inline compute/disks/disks_test.go:464]: Same as above. Split this into two lines.

**Review by telpirion — CHANGES_REQUESTED** [review]

File: compute/disks/disks_test.go (hunk 3 above)
Comment (telpirion) [reply compute/disks/disks_test.go]: Yep, that's fine.
